export interface Question {
  id: string;
  text: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correct: number; // 1-4
  explanation: string;
  subject: string;
  difficulty: string;
}

export const questionBank: Question[] = [
  // PHYSICS (10 questions)
  {
    id: "phy1",
    text: "A body of mass 2 kg is thrown vertically upward with a velocity of 20 m/s. What is the kinetic energy at the highest point?",
    optionA: "400 J",
    optionB: "200 J",
    optionC: "0 J",
    optionD: "100 J",
    correct: 3,
    explanation: "At the highest point, velocity becomes zero, so kinetic energy = ½mv² = 0.",
    subject: "Physics",
    difficulty: "easy",
  },
  {
    id: "phy2",
    text: "The SI unit of electric charge is:",
    optionA: "Ampere",
    optionB: "Coulomb",
    optionC: "Volt",
    optionD: "Ohm",
    correct: 2,
    explanation: "The SI unit of electric charge is the Coulomb (C). One coulomb is the charge transported by a current of 1 ampere in 1 second.",
    subject: "Physics",
    difficulty: "easy",
  },
  {
    id: "phy3",
    text: "A convex lens of focal length 20 cm produces a real, inverted image of magnification 2. The object distance is:",
    optionA: "60 cm",
    optionB: "40 cm",
    optionC: "30 cm",
    optionD: "20 cm",
    correct: 3,
    explanation: "Using lens formula: 1/v - 1/u = 1/f. Given m = -v/u = 2, so v = -2u. Substituting: 1/(-2u) - 1/u = 1/20, solving gives u = -30 cm.",
    subject: "Physics",
    difficulty: "medium",
  },
  {
    id: "phy4",
    text: "Two resistors of 6Ω and 3Ω are connected in parallel. The equivalent resistance is:",
    optionA: "9Ω",
    optionB: "2Ω",
    optionC: "3Ω",
    optionD: "1Ω",
    correct: 2,
    explanation: "For parallel resistors: 1/R = 1/R₁ + 1/R₂ = 1/6 + 1/3 = 1/6 + 2/6 = 3/6 = 1/2. So R = 2Ω.",
    subject: "Physics",
    difficulty: "easy",
  },
  {
    id: "phy5",
    text: "The work done by a force is maximum when the angle between force and displacement is:",
    optionA: "0°",
    optionB: "45°",
    optionC: "90°",
    optionD: "180°",
    correct: 1,
    explanation: "Work = F × d × cosθ. Work is maximum when cosθ = 1, i.e., when θ = 0° (force and displacement are parallel).",
    subject: "Physics",
    difficulty: "easy",
  },
  {
    id: "phy6",
    text: "A capacitor of capacitance 10μF is charged to 100V. The energy stored is:",
    optionA: "0.05 J",
    optionB: "0.5 J",
    optionC: "50 J",
    optionD: "1000 J",
    correct: 1,
    explanation: "Energy stored in a capacitor = ½CV² = ½ × 10 × 10⁻⁶ × (100)² = ½ × 10⁻⁵ × 10⁴ = 0.05 J.",
    subject: "Physics",
    difficulty: "medium",
  },
  {
    id: "phy7",
    text: "The de Broglie wavelength of an electron accelerated through 100V is approximately:",
    optionA: "1.23 nm",
    optionB: "1.23 Å",
    optionC: "12.3 nm",
    optionD: "12.3 Å",
    correct: 1,
    explanation: "λ = h/√(2meV) = 12.27/√V Å = 12.27/√100 = 1.227 Å ≈ 1.23 Å.",
    subject: "Physics",
    difficulty: "hard",
  },
  {
    id: "phy8",
    text: "In a Young's double slit experiment, the fringe width is found to be 0.4 mm. If the whole apparatus is immersed in water (μ = 4/3), the new fringe width will be:",
    optionA: "0.3 mm",
    optionB: "0.53 mm",
    optionC: "0.6 mm",
    optionD: "0.8 mm",
    correct: 1,
    explanation: "Fringe width β = λD/d. In water, λ reduces by factor μ. New β = β/μ = 0.4/(4/3) = 0.3 mm.",
    subject: "Physics",
    difficulty: "hard",
  },
  {
    id: "phy9",
    text: "A body weighs 63 N on the surface of the earth. At a height equal to half the radius of earth, its weight will be:",
    optionA: "28 N",
    optionB: "31.5 N",
    optionC: "14 N",
    optionD: "7 N",
    correct: 1,
    explanation: "g' = g × R²/(R+h)² = g × R²/(3R/2)² = g × 4/9. Weight = 63 × 4/9 = 28 N.",
    subject: "Physics",
    difficulty: "medium",
  },
  {
    id: "phy10",
    text: "The dimensional formula of Planck's constant is:",
    optionA: "[ML²T⁻¹]",
    optionB: "[ML²T⁻²]",
    optionC: "[MLT⁻¹]",
    optionD: "[ML⁻¹T⁻¹]",
    correct: 1,
    explanation: "Planck's constant h has units of J·s = kg·m²·s⁻²·s = kg·m²·s⁻¹, so the dimensional formula is [ML²T⁻¹].",
    subject: "Physics",
    difficulty: "medium",
  },

  // CHEMISTRY (10 questions)
  {
    id: "chem1",
    text: "The IUPAC name of CH₃-CH(OH)-CH₃ is:",
    optionA: "Propan-1-ol",
    optionB: "Propan-2-ol",
    optionC: "Isopropyl alcohol only",
    optionD: "2-Methyl ethanol",
    correct: 2,
    explanation: "CH₃-CH(OH)-CH₃ is propan-2-ol (IUPAC name). The -OH group is on the second carbon of a three-carbon chain.",
    subject: "Chemistry",
    difficulty: "easy",
  },
  {
    id: "chem2",
    text: "Which of the following has the highest ionization energy?",
    optionA: "Na",
    optionB: "Mg",
    optionC: "Al",
    optionD: "Ne",
    correct: 4,
    explanation: "Neon (Ne) is a noble gas with a complete octet, making it extremely difficult to remove an electron. It has the highest ionization energy among the given options.",
    subject: "Chemistry",
    difficulty: "easy",
  },
  {
    id: "chem3",
    text: "The hybridization of carbon in methane (CH₄) is:",
    optionA: "sp",
    optionB: "sp²",
    optionC: "sp³",
    optionD: "sp³d",
    correct: 3,
    explanation: "In methane, carbon forms 4 sigma bonds with hydrogen atoms, requiring 4 hybrid orbitals. This is achieved through sp³ hybridization.",
    subject: "Chemistry",
    difficulty: "easy",
  },
  {
    id: "chem4",
    text: "What is the pH of a 0.001 M HCl solution?",
    optionA: "1",
    optionB: "2",
    optionC: "3",
    optionD: "4",
    correct: 3,
    explanation: "HCl is a strong acid that dissociates completely. [H⁺] = 0.001 M = 10⁻³ M. pH = -log(10⁻³) = 3.",
    subject: "Chemistry",
    difficulty: "easy",
  },
  {
    id: "chem5",
    text: "In the reaction N₂ + 3H₂ → 2NH₃, if 28g of N₂ reacts with 6g of H₂, the limiting reagent is:",
    optionA: "N₂",
    optionB: "H₂",
    optionC: "Both react completely",
    optionD: "Neither",
    correct: 2,
    explanation: "Moles of N₂ = 28/28 = 1 mol. Moles of H₂ = 6/2 = 3 mol. Required H₂ for 1 mol N₂ = 3 mol. Available H₂ = 3 mol (exactly needed). But the reaction requires H₂ in a 3:1 ratio. Since we have exactly 3 mol H₂ for 1 mol N₂, both should theoretically react completely. However, in practice, N₂ is often the limiting reagent due to the stoichiometric balance.",
    subject: "Chemistry",
    difficulty: "medium",
  },
  {
    id: "chem6",
    text: "The oxidation state of Mn in KMnO₄ is:",
    optionA: "+4",
    optionB: "+5",
    optionC: "+6",
    optionD: "+7",
    correct: 4,
    explanation: "Let oxidation state of Mn = x. K(+1) + Mn(x) + 4O(-2) = 0. 1 + x - 8 = 0, x = +7.",
    subject: "Chemistry",
    difficulty: "easy",
  },
  {
    id: "chem7",
    text: "Which of the following is the strongest acid?",
    optionA: "HF",
    optionB: "HCl",
    optionC: "HBr",
    optionD: "HI",
    correct: 4,
    explanation: "Among hydrogen halides, acidity increases down the group due to decreasing bond strength. HI has the weakest H-I bond, making it the strongest acid.",
    subject: "Chemistry",
    difficulty: "medium",
  },
  {
    id: "chem8",
    text: "The number of sigma and pi bonds in benzene are respectively:",
    optionA: "6, 3",
    optionB: "12, 3",
    optionC: "9, 3",
    optionD: "12, 6",
    correct: 2,
    explanation: "Benzene has 6 C-C sigma bonds, 6 C-H sigma bonds = 12 sigma bonds. It has 3 delocalized pi bonds in the ring.",
    subject: "Chemistry",
    difficulty: "medium",
  },
  {
    id: "chem9",
    text: "The crystal field splitting energy (Δ₀) for [Fe(CN)₆]³⁻ is higher than [FeF₆]³⁻ because:",
    optionA: "CN⁻ is a weak field ligand",
    optionB: "CN⁻ is a strong field ligand",
    optionC: "F⁻ has greater charge",
    optionD: "Fe³⁺ changes oxidation state",
    correct: 2,
    explanation: "CN⁻ is a strong field ligand (high in spectrochemical series) and causes large crystal field splitting. F⁻ is a weak field ligand with smaller splitting.",
    subject: "Chemistry",
    difficulty: "hard",
  },
  {
    id: "chem10",
    text: "The rate constant of a first-order reaction is 0.0693 min⁻¹. The half-life of the reaction is:",
    optionA: "10 min",
    optionB: "100 min",
    optionC: "20 min",
    optionD: "50 min",
    correct: 1,
    explanation: "For first-order reaction, t½ = 0.693/k = 0.693/0.0693 = 10 min.",
    subject: "Chemistry",
    difficulty: "medium",
  },

  // BIOLOGY (10 questions)
  {
    id: "bio1",
    text: "The powerhouse of the cell is:",
    optionA: "Nucleus",
    optionB: "Ribosome",
    optionC: "Mitochondria",
    optionD: "Golgi apparatus",
    correct: 3,
    explanation: "Mitochondria are called the powerhouse of the cell because they produce ATP (energy currency) through cellular respiration.",
    subject: "Biology",
    difficulty: "easy",
  },
  {
    id: "bio2",
    text: "DNA replication is described as:",
    optionA: "Conservative",
    optionB: "Semi-conservative",
    optionC: "Dispersive",
    optionD: "Random",
    correct: 2,
    explanation: "DNA replication is semi-conservative, as proved by Meselson and Stahl experiment. Each new DNA molecule has one old strand and one new strand.",
    subject: "Biology",
    difficulty: "easy",
  },
  {
    id: "bio3",
    text: "Which of the following is NOT a function of the liver?",
    optionA: "Bile production",
    optionB: "Detoxification",
    optionC: "Insulin production",
    optionD: "Glycogen storage",
    correct: 3,
    explanation: "Insulin is produced by the beta cells of the pancreas, not the liver. The liver produces bile, detoxifies substances, and stores glycogen.",
    subject: "Biology",
    difficulty: "easy",
  },
  {
    id: "bio4",
    text: "The process of conversion of sugar into alcohol by yeast is called:",
    optionA: "Respiration",
    optionB: "Fermentation",
    optionC: "Photosynthesis",
    optionD: "Digestion",
    correct: 2,
    explanation: "Fermentation is the anaerobic process by which yeast converts sugars (glucose) into ethanol and carbon dioxide.",
    subject: "Biology",
    difficulty: "easy",
  },
  {
    id: "bio5",
    text: "In Mendel's monohybrid cross, the phenotypic ratio in F2 generation is:",
    optionA: "1:2:1",
    optionB: "3:1",
    optionC: "1:1",
    optionD: "9:3:3:1",
    correct: 2,
    explanation: "In a monohybrid cross, the F2 generation shows a phenotypic ratio of 3 dominant : 1 recessive = 3:1.",
    subject: "Biology",
    difficulty: "easy",
  },
  {
    id: "bio6",
    text: "The oxygen evolved during photosynthesis comes from:",
    optionA: "CO₂",
    optionB: "H₂O",
    optionC: "Both CO₂ and H₂O",
    optionD: "Glucose",
    correct: 2,
    explanation: "The oxygen evolved during photosynthesis comes from the photolysis (splitting) of water molecules, not from CO₂. This was proved by Ruben and Kamen using ¹⁸O.",
    subject: "Biology",
    difficulty: "medium",
  },
  {
    id: "bio7",
    text: "Which of the following hormones is secreted by the adrenal medulla?",
    optionA: "Cortisol",
    optionB: "Aldosterone",
    optionC: "Adrenaline",
    optionD: "ACTH",
    correct: 3,
    explanation: "The adrenal medulla secretes adrenaline (epinephrine) and noradrenaline (norepinephrine), which are emergency hormones (fight or flight response).",
    subject: "Biology",
    difficulty: "medium",
  },
  {
    id: "bio8",
    text: "The number of chromosomes in a human somatic cell is:",
    optionA: "23",
    optionB: "44",
    optionC: "46",
    optionD: "48",
    correct: 3,
    explanation: "Human somatic (body) cells are diploid (2n) and contain 46 chromosomes (23 pairs). Gametes are haploid with 23 chromosomes.",
    subject: "Biology",
    difficulty: "easy",
  },
  {
    id: "bio9",
    text: "Which enzyme unwinds the DNA double helix during replication?",
    optionA: "DNA polymerase",
    optionB: "Ligase",
    optionC: "Helicase",
    optionD: "Primase",
    correct: 3,
    explanation: "Helicase is the enzyme that unwinds the DNA double helix by breaking hydrogen bonds between base pairs at the replication fork.",
    subject: "Biology",
    difficulty: "medium",
  },
  {
    id: "bio10",
    text: "The functional unit of the kidney is called:",
    optionA: "Neuron",
    optionB: "Nephron",
    optionC: "Alveolus",
    optionD: "Sarcomere",
    correct: 2,
    explanation: "The nephron is the functional unit of the kidney. Each kidney contains about 1 million nephrons responsible for filtration, reabsorption, and secretion.",
    subject: "Biology",
    difficulty: "easy",
  },

  // MATHS (10 questions)
  {
    id: "math1",
    text: "The derivative of sin(x²) with respect to x is:",
    optionA: "cos(x²)",
    optionB: "2x·cos(x²)",
    optionC: "x²·cos(x²)",
    optionD: "2·sin(x)·cos(x)",
    correct: 2,
    explanation: "Using chain rule: d/dx[sin(x²)] = cos(x²) · d/dx(x²) = cos(x²) · 2x = 2x·cos(x²).",
    subject: "Maths",
    difficulty: "easy",
  },
  {
    id: "math2",
    text: "The value of ∫₀¹ x² dx is:",
    optionA: "1/2",
    optionB: "1/3",
    optionC: "1/4",
    optionD: "1",
    correct: 2,
    explanation: "∫₀¹ x² dx = [x³/3]₀¹ = (1/3) - 0 = 1/3.",
    subject: "Maths",
    difficulty: "easy",
  },
  {
    id: "math3",
    text: "If A is a 2×2 matrix with |A| = 5, then |3A| is:",
    optionA: "15",
    optionB: "30",
    optionC: "45",
    optionD: "225",
    correct: 3,
    explanation: "For a 2×2 matrix, |kA| = k²|A|. So |3A| = 3² × 5 = 9 × 5 = 45.",
    subject: "Maths",
    difficulty: "medium",
  },
  {
    id: "math4",
    text: "The general solution of the differential equation dy/dx = y/x is:",
    optionA: "y = kx",
    optionB: "y = k/x",
    optionC: "y = kx²",
    optionD: "y = ke^x",
    correct: 1,
    explanation: "dy/y = dx/x. Integrating: ln|y| = ln|x| + ln|k|. So y = kx.",
    subject: "Maths",
    difficulty: "medium",
  },
  {
    id: "math5",
    text: "The value of lim(x→0) sin(x)/x is:",
    optionA: "0",
    optionB: "1",
    optionC: "∞",
    optionD: "Undefined",
    correct: 2,
    explanation: "This is a standard limit. lim(x→0) sin(x)/x = 1. This can be proved using the squeeze theorem or L'Hôpital's rule.",
    subject: "Maths",
    difficulty: "easy",
  },
  {
    id: "math6",
    text: "Two vectors a⃗ and b⃗ are perpendicular if:",
    optionA: "|a⃗| = |b⃗|",
    optionB: "a⃗ · b⃗ = 1",
    optionC: "a⃗ · b⃗ = 0",
    optionD: "a⃗ × b⃗ = 0",
    correct: 3,
    explanation: "Two vectors are perpendicular (orthogonal) when their dot product equals zero: a⃗ · b⃗ = |a⃗||b⃗|cos90° = 0.",
    subject: "Maths",
    difficulty: "easy",
  },
  {
    id: "math7",
    text: "The sum of the first n terms of an AP is 3n² + 5n. The 10th term is:",
    optionA: "58",
    optionB: "62",
    optionC: "65",
    optionD: "350",
    correct: 2,
    explanation: "Sₙ = 3n² + 5n. aₙ = Sₙ - Sₙ₋₁ = (3n² + 5n) - [3(n-1)² + 5(n-1)] = 6n + 2. So a₁₀ = 60 + 2 = 62.",
    subject: "Maths",
    difficulty: "medium",
  },
  {
    id: "math8",
    text: "If f(x) = x³ - 3x² + 2, then the point of inflection is at:",
    optionA: "x = 0",
    optionB: "x = 1",
    optionC: "x = 2",
    optionD: "x = 3",
    correct: 2,
    explanation: "f''(x) = 6x - 6 = 0 gives x = 1. At x = 1, the sign of f''(x) changes, so it's a point of inflection.",
    subject: "Maths",
    difficulty: "medium",
  },
  {
    id: "math9",
    text: "The number of 4-digit numbers that can be formed using digits 1, 2, 3, 4, 5 (repetition allowed) such that the number is divisible by 4 is:",
    optionA: "100",
    optionB: "125",
    optionC: "150",
    optionD: "175",
    correct: 2,
    explanation: "A number is divisible by 4 if its last two digits form a number divisible by 4. There are 5 choices for each of the first two digits and for the last two digits, the divisible-by-4 pairs from {1,2,3,4,5} are: 12, 24, 32, 44, 52 — that's 5 pairs. Total = 5 × 5 × 5 = 125.",
    subject: "Maths",
    difficulty: "hard",
  },
  {
    id: "math10",
    text: "The area bounded by the curve y = x², x-axis, x = 0 and x = 2 is:",
    optionA: "4/3 sq units",
    optionB: "8/3 sq units",
    optionC: "2 sq units",
    optionD: "4 sq units",
    correct: 2,
    explanation: "Area = ∫₀² x² dx = [x³/3]₀² = 8/3 - 0 = 8/3 sq units.",
    subject: "Maths",
    difficulty: "medium",
  },
];

export function getQuestionsByCategory(category: string, count: number = 10): Question[] {
  let pool = questionBank;
  if (category !== "Mixed") {
    pool = questionBank.filter((q) => q.subject === category);
  }
  // Shuffle and take count
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

export function getSubjects(): string[] {
  return ["Physics", "Chemistry", "Biology", "Maths"];
}

export const levelTitles: Record<number, { title: string; minXP: number }> = {
  1: { title: "Beginner", minXP: 0 },
  2: { title: "Learner", minXP: 100 },
  3: { title: "Student", minXP: 300 },
  4: { title: "Scholar", minXP: 600 },
  5: { title: "Scholar", minXP: 1000 },
  6: { title: "Scholar", minXP: 1500 },
  7: { title: "Scholar", minXP: 2100 },
  8: { title: "Scholar", minXP: 2800 },
  9: { title: "Expert", minXP: 3600 },
  10: { title: "Expert", minXP: 4500 },
  11: { title: "Expert", minXP: 5500 },
  12: { title: "Expert", minXP: 6600 },
  13: { title: "Expert", minXP: 7800 },
  14: { title: "Expert", minXP: 9100 },
  15: { title: "Master", minXP: 10500 },
  16: { title: "Master", minXP: 12000 },
  17: { title: "Master", minXP: 13600 },
  18: { title: "Master", minXP: 15300 },
  19: { title: "Master", minXP: 17100 },
  20: { title: "Topper", minXP: 19000 },
  21: { title: "Topper", minXP: 21000 },
  22: { title: "Topper", minXP: 23100 },
  23: { title: "Topper", minXP: 25300 },
  24: { title: "Topper", minXP: 27600 },
  25: { title: "Topper", minXP: 30000 },
  26: { title: "Legend", minXP: 32500 },
  27: { title: "Legend", minXP: 35100 },
  28: { title: "Legend", minXP: 37800 },
  29: { title: "Legend", minXP: 40600 },
  30: { title: "Legend", minXP: 43500 },
};

export function getLevelFromXP(xp: number): { level: number; title: string; currentLevelXP: number; nextLevelXP: number; progress: number } {
  const levels = Object.entries(levelTitles)
    .map(([k, v]) => ({ level: parseInt(k), ...v }))
    .sort((a, b) => a.level - b.level);

  let currentLevel = levels[0];
  let nextLevel = levels[1] || levels[0];

  for (let i = levels.length - 1; i >= 0; i--) {
    if (xp >= levels[i].minXP) {
      currentLevel = levels[i];
      nextLevel = levels[i + 1] || { level: levels[i].level + 1, minXP: levels[i].minXP + 5000 };
      break;
    }
  }

  const range = nextLevel.minXP - currentLevel.minXP;
  const progress = range > 0 ? ((xp - currentLevel.minXP) / range) * 100 : 100;

  return {
    level: currentLevel.level,
    title: currentLevel.title,
    currentLevelXP: currentLevel.minXP,
    nextLevelXP: nextLevel.minXP,
    progress: Math.min(100, progress),
  };
}

export const achievementDefs = [
  { type: "first_game", name: "First Game", description: "Complete your first quiz game", icon: "🎮" },
  { type: "perfect_score", name: "Perfect Score", description: "Get 10/10 in a battle", icon: "💯" },
  { type: "speed_demon", name: "Speed Demon", description: "Answer 5 questions in under 5 seconds each", icon: "⚡" },
  { type: "streak_7", name: "7-Day Streak", description: "Play for 7 consecutive days", icon: "🔥" },
  { type: "combo_king", name: "Combo King", description: "Achieve a x5 combo", icon: "👑" },
  { type: "100_questions", name: "Century Club", description: "Answer 100 questions total", icon: "💯" },
  { type: "500_questions", name: "Question Machine", description: "Answer 500 questions total", icon: "🤖" },
  { type: "subject_master", name: "Subject Master", description: "Play all 4 subjects in battle mode", icon: "📚" },
];
